baseURL: /
locale: en-uk
build:
  writeStats: true
title: Tobi Ayodele


params:
  author: Tobi Ayodele
  description: Tobi Ayodele Computer Science portfolio/blog
  copyright: © 2026 Tobi Ayodele · powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: projects
    - item: experience
    - item: education
    - item: skills
      panel_id: skill-panel
    - item: hobbies

security:
  exec:
    allow:
      - '^(dart-)?sass$'
      - '^go$'
      - '^git$'
      - '^node$'
      - '^postcss$'
      - '^tailwindcss$'
